### ISSUE TITLE
image feature extraction question

### ISSUE THREAD

**Issue by fakecan** [Cassie07/PathOmics#1]
1. How does the WSI patching process work?
2. Facing the problem of missing npy files.
This is probably because there is no image feature extraction process.
Do you have a script for image feature extraction? Or can you tell me how to proceed?

Thanks for doing the research.

**Comment by Cassie07** [comment]
Hi @fakecan, thanks for your interest in our work. The following are the answers to your questions:

A1. The WSI image is processed into patches (e.g., 512x512), and we remove background patches (e.g., regions without any tissue).

A2. You need to generate npy files by yourself. The feature-extraction-related code is in https://github.com/Cassie07/PathOmics/blob/main/PathOmics/split_tiles_utils

You can check the customized ResNet architecture we used at https://github.com/Cassie07/PathOmics/blob/main/PathOmics/split_tiles_utils/Customized_resnet.py

The feature extractor code is at https://github.com/Cassie07/PathOmics/blob/main/PathOmics/split_tiles_utils/helper.py

Based on these details, you can extract features from WSI patches.

Please feel free to let me know if you have any questions. Also, please cite our paper if you find it helpful for your research.

Bests,
Kexin
