### ISSUE TITLE
About Pathology Feature extraction shape

### ISSUE THREAD

**Issue by zhengbiqing** [Cassie07/PathOmics#10]
Thank for your great work! 
I have a question and please give me a help.

Different WSI has different size and will be cut in different amount small images (for example 256*256). Each small image correspond to a feature (for example, as a tensor of 1*1024). So different WSI has different shape feature (for example, N*1024, M*1024). How does these different shape features as input to model and train the model?

Looking forward to your answer. Thanks very much!

**Comment by Cassie07** [comment]
Hi @zhengbiqing, Thanks for your interest in our study! We set the batch size to 1. So when you load the data by data loader, you do not have to force the number of patches to be the same for each patient. Please feel free to let me know if you have any other questions.
