### ISSUE TITLE
data_clinical_patient_modified.csv

### ISSUE THREAD

**Issue by sunkevin101** [Cassie07/PathOmics#11]
Hi, thank for your great work!
I have a question and please give me a help.

how do you get "./data_clinical_patient_modified.csv"?

Thank you again

**Comment by Cassie07** [comment]
Hi @KevinSUN-Mac, Thanks for your interest in our study. " /data_clinical_patient_modified.csv" is downloaded from CBioPortal. You can directly use data_clinical_patient.txt in the original dataset. I removed the first three rows of the original table and set the fourth row as the header of the table. Please feel free to let me know if you have any other questions about the clinical data.
