### ISSUE TITLE
image feature extraction

### ISSUE THREAD

**Issue by 20373243** [Cassie07/PathOmics#3]
1.how can we get the floder ‘TCGA-COAD/Extracted_feature' ?
2.how can we generate npy files?

**Comment by Cassie07** [comment]
Hello @20373243 ! Thanks for your interest in our work. The following are the answers to your questions:

1. You need to extract the patch features and save them into TCGA-COAD/Extracted_feature folder on your server.
2. Similar to question 1, you need to extract patch features by yourself and save them in npy format. 

All of the raw image data can be accessed on the TCGA database (i.e., GDC data portal). For the detailed patch feature extraction steps, please check [data preprocessing](https://github.com/Cassie07/PathOmics/tree/main?tab=readme-ov-file#data-prerpocessing) in our readme file. Also, please feel free to check the related discussion in [Issue 1](https://github.com/Cassie07/PathOmics/issues/1).

Please feel free to let me know if you have any questions. Also, please cite our paper if you find it helpful for your research.

Bests,
Kexin

**Comment by 20373243** [comment]
I see " Extract patch features via pretrained models (e.g., ImageNet-pretrained ResNet101) " from  data preprocessing, and I want to know how can we get pretrained models?  pre-trained models trained from a natural image set or  pre-trained models trained from this code?
Thanks for your research and looking for your reply.

**Comment by Cassie07** [comment]
@20373243 Please check the following pretrain model weights from [model url](https://github.com/Cassie07/PathOmics/blob/main/PathOmics/split_tiles_utils/Customized_resnet.py#L13C1-L13C12) in our code. The pretrained weights are provided by the official PyTorch directly. I believe the pretrained models are trained from natural images. When you set the model as `model = Customized_resnet.resnet50_baseline(pretrained=True)`, the pretrain weights will be automatically downloaded . For more details, please check PyTorch official documents.

Please feel free to let me know if you have any questions. 

Bests,
Kexin

**Comment by nyg919** [comment]
"Hello, can you provide me with a URL for downloading the raw data? I couldn't find it."

**Comment by Cassie07** [comment]
> "Hello, can you provide me with a URL for downloading the raw data? I couldn't find it."

@nyg919 Hello! Thanks for your interest in our study. Please download genomics data via [cBioPortal](https://www.cbioportal.org/study/summary?id=coadread_tcga_pan_can_atlas_2018) and access WSI via [TCGA database](https://portal.gdc.cancer.gov/). Please feel free to let me know if you have further questions.

Bests,
Kexin
