### ISSUE TITLE
feature dimension

### ISSUE THREAD

**Issue by gaogehan** [Cassie07/PathOmics#4]
Thanks for your grate work! In bash_main.py, default feature_dimension is 1024. However, resnet 50 and 101 generates feature dimension 2048; resnet 18  generates feature dimension 512. How to get feature dimension 1024?

**Comment by gaogehan** [comment]
I have noticed the Customized_resnet.py to get feature_dimension 1024.

**Comment by Cassie07** [comment]
@gaogehan Good to know that. Please feel free to let me know if you have any other questions.
