### ISSUE TITLE
Question for group-wise WSIs representation

### ISSUE THREAD

**Issue by Nerovix** [Cassie07/PathOmics#8]
Thank you for this research! I am a beginner and I have a question to ask. Why do we need to group image features during pre-training? The grouping is integrated into eight 1×256 vectors. Finally, global attention is used to synthesize a 1×256 vector. Why not do it directly on the data before grouping, and directly add some layers of the network after the K×1024 vector extracted from the original WSI and get a 1×256 vector?

感谢你们的这项研究！我是一个初学者，有一个问题想请教一下，请问在预训练中为什么要对图像特征分组呢？分组整合为8个1×256的向量最后还要用全局注意力合成一个1×256的向量，为什么不直接对分组前的数据做，直接把大小为K×1024的数据提取出来的向量通过加几层网络变成1×256的向量呢？

**Comment by Cassie07** [comment]
@Nerovix Hello! Thanks for your interest in our study! We grouped images to achieve a better feature reduction. We also did a few ablation studies to determine whether we needed to use the group image features and the proper number of the image groups. Please feel free to use a different number of image groups or not use a group based on your own study. Please feel free to let me know if you have any questions. Also, please cite our paper if you find it helpful for your research.

Bests,
Kexin
