### ISSUE TITLE
About preprocessing of WSIs

### ISSUE THREAD

**Issue by Elliot-QxZhang** [Cassie07/PathOmics#9]
Hi! Thanks for your work. But I cannot find the preprocessing, e.g., the patching code, and I don't know which magnification you use in your work. Can you share the preprocessing codes to increase reproducibility?

**Comment by Cassie07** [comment]
Hi @Elliot-QxZhang , Thanks for your interest in our study! The magnification of WSIs is 40x for all of our studies. You can also use the data preprocessing code in our previous publications on [The Lancet Digital Health](https://github.com/Cassie07/Review_Molecular_profile_prediction_GNN) as the reference. Please feel free to let me know if you are unclear on any other parameters or settings.
